### ISSUE TITLE
Washing machine delay

### ISSUE THREAD

**Issue by Edzilla2000** [Vasiley/Home-Assistant-Main#4]
I've been using your washing machine package for a while and it works great, except that I have false positives where I'm alerted that the laundry is done when it is not.

It seems my washer sometimes stops consuming energy for a while during a wash, especially with lower programs light "nightwash".
Do you think your package could be adapted to add a delay? For example wait 5 minutes after the washer goes below the limit and only alert if it stays below that level?

**Comment by Vasiley** [comment]
```
  - alias: 'Washer Done'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.washing_machine_power_down
        from: 'False'
        to: 'True'
        for:
          minutes: 3
```
change the minutes there to your desire ..basically that is the delay ....so try 5 but washer may finish and not tell you for a few minutes
